global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-llm-server'
    static_configs:
      - targets: ['node-llm-server:3000']
    metrics_path: '/metrics'  # Vous devrez ajouter une route /metrics dans votre serveur Express

  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']